<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <!-- KNI soporta net8.0 para WASM. -->
    <TargetFramework>net8.0</TargetFramework>
	  <Configurations>Debug;Release;YTB</Configurations>
	  <MonoGamePlatform>Web</MonoGamePlatform>
    <AssemblyName>SandBoxGame</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- Optimizaciones de WASM -->
    <RunAOTCompilation>false</RunAOTCompilation>
    <ContentOutput>$(ProjectDir)wwwroot\</ContentOutput>
  </PropertyGroup>

  <!-- UseV2=true se propaga transitivamente a Core, YotsubaEngine, Gum, etc. -->
  <ItemGroup>
    <ProjectReference Include="..\SharedCode.Multiplatform\SharedCode.Multiplatform.NoMobile.csproj" 
                      AdditionalProperties="UseV2=true"
                      SetTargetFramework="TargetFramework=net8.0" />
  </ItemGroup>

  <ItemGroup>
    <!-- KNI Blazor web backend -->
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.*" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.*" />
    <PackageReference Include="nkast.Kni.Platform.Blazor.GL" Version="4.2.9001" />
  </ItemGroup>

  <Target Name="CopyCoreContent" BeforeTargets="BeforeBuild">
    <!-- Copiamos el proyecto Gum de Core/Content hacia wwwroot y wwwroot/Content -->
    <ItemGroup>
      <GumContentFiles Include="..\SandBoxGame.Core\Content\**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(GumContentFiles)" DestinationFolder="wwwroot\%(RecursiveDir)" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(GumContentFiles)" DestinationFolder="wwwroot\Content\%(RecursiveDir)" SkipUnchangedFiles="true" />
  </Target>

  <Import Project="..\SandBoxGame.Content\BuildContent.targets" />
</Project>
