// <auto-generated>
// Este archivo es regenerado por YTBContentBuilder.YTBFileToGameDataGenerator
// a partir de los atributos [UIComponent]/[UIComponentValue] del engine. NO EDITAR.
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;
using YotsubaEngine.Core.Component.C_2D;
using YotsubaEngine.Core.Component.C_3D;
using YotsubaEngine.Core.Component.C_AGNOSTIC;
using YotsubaEngine.Physics;
using YotsubaEngine.Physics.RigidBody;
using YotsubaEngine.Core.YotsubaGame;

namespace YotsubaEngine.ActionFiles.YTB_Files
{
 public partial class YTBFileToGameData
 {
 private static bool _G_TryParseVector2(string raw, out Vector2 v)
{
    v = Vector2.Zero;
    if (string.IsNullOrEmpty(raw)) return false;
    var parts = raw.Split(',');
    if (parts.Length < 2) return false;
    if (float.TryParse(parts[0], NumberStyles.Float, CultureInfo.InvariantCulture, out var x)
        && float.TryParse(parts[1], NumberStyles.Float, CultureInfo.InvariantCulture, out var y))
    { v = new Vector2(x, y); return true; }
    return false;
}

private static bool _G_TryParseVector3(string raw, out Vector3 v)
{
    v = Vector3.Zero;
    if (string.IsNullOrEmpty(raw)) return false;
    var parts = raw.Split(',');
    if (parts.Length < 3) return false;
    if (float.TryParse(parts[0], NumberStyles.Float, CultureInfo.InvariantCulture, out var x)
        && float.TryParse(parts[1], NumberStyles.Float, CultureInfo.InvariantCulture, out var y)
        && float.TryParse(parts[2], NumberStyles.Float, CultureInfo.InvariantCulture, out var z))
    { v = new Vector3(x, y, z); return true; }
    return false;
}

private static bool _G_TryParseRectangle(string raw, out Rectangle r)
{
    r = default;
    if (string.IsNullOrEmpty(raw)) return false;
    var parts = raw.Split(',');
    if (parts.Length < 4) return false;
    if (int.TryParse(parts[0], out var x) && int.TryParse(parts[1], out var y)
        && int.TryParse(parts[2], out var w) && int.TryParse(parts[3], out var h))
    { r = new Rectangle(x, y, w, h); return true; }
    return false;
}

private static bool _G_ShouldSkip(string[]? exclude, string name)
{
    if (exclude == null || exclude.Length == 0) return false;
    for (int i = 0; i < exclude.Length; i++) if (exclude[i] == name) return true;
    return false;
}

        internal static RigidBodyComponent3D ParseRigidBodyComponent3D_Generated(
            YTBComponents comp, string sceneName, string entityName, string[]? exclude = null)
        {
            var result = new RigidBodyComponent3D();
            foreach (var prop in comp.Propiedades)
            {
                if (_G_ShouldSkip(exclude, prop.Item1)) continue;
                switch (prop.Item1)
                {
                    case "CollisionLayer":
                    {
                        if (Enum.TryParse<CollisionLayer>(prop.Item2, true, out var v)) result.CollisionLayer = v;
                        break;
                    }
                    case "Velocity":
                    {
                        if (_G_TryParseVector3(prop.Item2, out var v)) result.Velocity = v;
                        break;
                    }
                }
            }
            return result;
        }

        internal static ModelComponent3D ParseModelComponent3D_Generated(
            YTBComponents comp, string sceneName, string entityName, string[]? exclude = null)
        {
            var result = new ModelComponent3D();
            foreach (var prop in comp.Propiedades)
            {
                if (_G_ShouldSkip(exclude, prop.Item1)) continue;
                switch (prop.Item1)
                {
                    case "ModelPath":
                    {
                        result.ModelPath = prop.Item2;
                        break;
                    }
                    case "IsVisible":
                    {
                        if (bool.TryParse(prop.Item2, out var v)) result.IsVisible = v;
                        break;
                    }
                    case "SphereRadius":
                    {
                        if (float.TryParse(prop.Item2, NumberStyles.Float, CultureInfo.InvariantCulture, out var v)) result.RadiusSphere = v;
                        break;
                    }
                    case "OffsetSphere":
                    {
                        if (_G_TryParseVector3(prop.Item2, out var v)) result.SphereOffset = v;
                        break;
                    }
                }
            }
            return result;
        }

        internal static InputComponent ParseInputComponent_Generated(
            YTBComponents comp, string sceneName, string entityName, string[]? exclude = null)
        {
            var result = new InputComponent();
            foreach (var prop in comp.Propiedades)
            {
                if (_G_ShouldSkip(exclude, prop.Item1)) continue;
                switch (prop.Item1)
                {
                    case "InputsInUse":
                    {
                        result.InputsInUse = prop.Item2;
                        break;
                    }
                    case "KeyboardMappings":
                    {
                        result.KeyboardMappings = prop.Item2;
                        break;
                    }
                    case "GamePadIndex":
                    {
                        if (Enum.TryParse<PlayerIndex>(prop.Item2, true, out var v)) result.GamePadIndex = v;
                        break;
                    }
                    case "MouseMappings":
                    {
                        result.MouseMappings = prop.Item2;
                        break;
                    }
                }
            }
            return result;
        }

        internal static ShaderComponent ParseShaderComponent_Generated(
            YTBComponents comp, string sceneName, string entityName, string[]? exclude = null)
        {
            var result = new ShaderComponent();
            foreach (var prop in comp.Propiedades)
            {
                if (_G_ShouldSkip(exclude, prop.Item1)) continue;
                switch (prop.Item1)
                {
                    case "ShaderPath":
                    {
                        result.ShaderPath = prop.Item2;
                        break;
                    }
                    case "IsActive":
                    {
                        if (bool.TryParse(prop.Item2, out var v)) result.IsActive = v;
                        break;
                    }
                    case "params":
                    {
                        result.Params = prop.Item2;
                        break;
                    }
                }
            }
            return result;
        }

        internal static TransformComponent ParseTransformComponent_Generated(
            YTBComponents comp, string sceneName, string entityName, string[]? exclude = null)
        {
            var result = new TransformComponent();
            foreach (var prop in comp.Propiedades)
            {
                if (_G_ShouldSkip(exclude, prop.Item1)) continue;
                switch (prop.Item1)
                {
                    case "Size":
                    {
                        if (_G_TryParseVector3(prop.Item2, out var v)) result.Size = v;
                        break;
                    }
                    case "Scale":
                    {
                        if (float.TryParse(prop.Item2, NumberStyles.Float, CultureInfo.InvariantCulture, out var v)) result.Scale = v;
                        break;
                    }
                    case "Rotation":
                    {
                        if (float.TryParse(prop.Item2, NumberStyles.Float, CultureInfo.InvariantCulture, out var v)) result.Rotation = v;
                        break;
                    }
                    case "Position":
                    {
                        if (_G_TryParseVector3(prop.Item2, out var v)) result.Position = v;
                        break;
                    }
                    case "SpriteEffects":
                    {
                        if (Enum.TryParse<SpriteEffects>(prop.Item2, true, out var v)) result.SpriteEffects = v;
                        break;
                    }
                    case "Color":
                    {
                        if (NamedColors.TryGetValue(prop.Item2, out var v)) result.Color = v;
                        break;
                    }
                }
            }
            return result;
        }

        internal static ScriptComponent ParseScriptComponent_Generated(
            YTBComponents comp, string sceneName, string entityName, string[]? exclude = null)
        {
            var result = new ScriptComponent();
            foreach (var prop in comp.Propiedades)
            {
                if (_G_ShouldSkip(exclude, prop.Item1)) continue;
                switch (prop.Item1)
                {
                    case "Scripts":
                    {
                        result.ScriptsRaw = prop.Item2;
                        break;
                    }
                }
            }
            return result;
        }

        internal static SpriteComponent2D ParseSpriteComponent2D_Generated(
            YTBComponents comp, string sceneName, string entityName, string[]? exclude = null)
        {
            var result = new SpriteComponent2D();
            foreach (var prop in comp.Propiedades)
            {
                if (_G_ShouldSkip(exclude, prop.Item1)) continue;
                switch (prop.Item1)
                {
                    case "TextureAtlasPath":
                    {
                        result.TextureAtlasPath = prop.Item2;
                        break;
                    }
                    case "SpriteName":
                    {
                        result.SpriteName = prop.Item2;
                        break;
                    }
                    case "SourceRectangle":
                    {
                        if (_G_TryParseRectangle(prop.Item2, out var v)) result.SourceRectangle = v;
                        break;
                    }
                    case "IsVisible":
                    {
                        if (bool.TryParse(prop.Item2, out var v)) result.IsVisible = v;
                        break;
                    }
                    case "2.5D":
                    {
                        if (bool.TryParse(prop.Item2, out var v)) result.Is2_5D = v;
                        break;
                    }
                }
            }
            return result;
        }

        internal static TileMapComponent2D ParseTileMapComponent2D_Generated(
            YTBComponents comp, string sceneName, string entityName, string[]? exclude = null)
        {
            var result = new TileMapComponent2D();
            foreach (var prop in comp.Propiedades)
            {
                if (_G_ShouldSkip(exclude, prop.Item1)) continue;
                switch (prop.Item1)
                {
                    case "TileMapPath":
                    {
                        result.TileMapPath = prop.Item2;
                        break;
                    }
                }
            }
            return result;
        }

        internal static ButtonComponent2D ParseButtonComponent2D_Generated(
            YTBComponents comp, string sceneName, string entityName, string[]? exclude = null)
        {
            var result = new ButtonComponent2D();
            foreach (var prop in comp.Propiedades)
            {
                if (_G_ShouldSkip(exclude, prop.Item1)) continue;
                switch (prop.Item1)
                {
                    case "IsActive":
                    {
                        if (bool.TryParse(prop.Item2, out var v)) result.IsActive = v;
                        break;
                    }
                    case "EffectiveArea":
                    {
                        if (_G_TryParseRectangle(prop.Item2, out var v)) result.EffectiveArea = v;
                        break;
                    }
                    case "Description":
                    {
                        result.Description = prop.Item2;
                        break;
                    }
                }
            }
            return result;
        }

        internal static RigidBodyComponent2D ParseRigidBodyComponent2D_Generated(
            YTBComponents comp, string sceneName, string entityName, string[]? exclude = null)
        {
            var result = new RigidBodyComponent2D();
            foreach (var prop in comp.Propiedades)
            {
                if (_G_ShouldSkip(exclude, prop.Item1)) continue;
                switch (prop.Item1)
                {
                    case "OffSetCollision":
                    {
                        if (_G_TryParseVector2(prop.Item2, out var v)) result.OffSetCollision = v;
                        break;
                    }
                    case "Velocity":
                    {
                        if (_G_TryParseVector3(prop.Item2, out var v)) result.Velocity = v;
                        break;
                    }
                    case "Collide":
                    {
                        if (Enum.TryParse<CollisionLevel>(prop.Item2, true, out var v)) result.Collide = v;
                        break;
                    }
                    case "Mass":
                    {
                        if (float.TryParse(prop.Item2, NumberStyles.Float, CultureInfo.InvariantCulture, out var v)) result.Mass = v;
                        break;
                    }
                }
            }
            return result;
        }

        internal static AnimationComponent2D ParseAnimationComponent2D_Generated(
            YTBComponents comp, string sceneName, string entityName, string[]? exclude = null)
        {
            var result = new AnimationComponent2D();
            foreach (var prop in comp.Propiedades)
            {
                if (_G_ShouldSkip(exclude, prop.Item1)) continue;
                switch (prop.Item1)
                {
                    case "TextureAtlasPath":
                    {
                        result.TextureAtlasPath = prop.Item2;
                        break;
                    }
                    case "AnimationBindings":
                    {
                        result.AnimationBindings = prop.Item2;
                        break;
                    }
                    case "CurrentAnimationType":
                    {
                        if (Enum.TryParse<AnimationType>(prop.Item2, true, out var v)) result.CurrentAnimationType = v;
                        break;
                    }
                }
            }
            return result;
        }

        internal static FontComponent2D ParseFontComponent2D_Generated(
            YTBComponents comp, string sceneName, string entityName, string[]? exclude = null)
        {
            var result = new FontComponent2D();
            foreach (var prop in comp.Propiedades)
            {
                if (_G_ShouldSkip(exclude, prop.Item1)) continue;
                switch (prop.Item1)
                {
                    case "Texto":
                    {
                        result.Texto = prop.Item2;
                        break;
                    }
                    case "Font":
                    {
                        result.Font = prop.Item2;
                        break;
                    }
                    case "IsVisible":
                    {
                        if (bool.TryParse(prop.Item2, out var v)) result.IsVisible = v;
                        break;
                    }
                }
            }
            return result;
        }

        /// <summary>
        /// Mapa generado en build-time con los valores 'inactivos' por componente y propiedad.
        /// Usado por <see cref="IsAllInactive"/> para decidir si un componente del .ytb debe saltarse.
        /// </summary>
        internal static readonly Dictionary<string, Dictionary<string, string>> _inactiveValuesByComponent =
            new(StringComparer.Ordinal)
        {
            ["ModelComponent3D"] = new(StringComparer.Ordinal)
            {
                ["CollisionLayer"] = "",
                ["Velocity"] = "",
            },
            ["ModelComponent3D"] = new(StringComparer.Ordinal)
            {
                ["ModelPath"] = "",
                ["IsVisible"] = "",
                ["SphereRadius"] = "",
                ["OffsetSphere"] = ",,",
            },
            ["InputComponent"] = new(StringComparer.Ordinal)
            {
                ["InputsInUse"] = "",
                ["KeyboardMappings"] = "",
                ["GamePadIndex"] = "",
                ["MouseMappings"] = "",
            },
            ["ShaderComponent"] = new(StringComparer.Ordinal)
            {
                ["ShaderPath"] = "",
                ["IsActive"] = "",
                ["params"] = "",
            },
            ["TransformComponent"] = new(StringComparer.Ordinal)
            {
                ["Size"] = ",,",
                ["Scale"] = "",
                ["Rotation"] = "",
                ["Position"] = ",,",
                ["SpriteEffects"] = "",
                ["Color"] = "",
            },
            ["ScriptComponent"] = new(StringComparer.Ordinal)
            {
                ["Scripts"] = "CSHARP&:&&;&",
            },
            ["SpriteComponent2D"] = new(StringComparer.Ordinal)
            {
                ["TextureAtlasPath"] = "",
                ["SpriteName"] = "",
                ["SourceRectangle"] = ",,,",
                ["IsVisible"] = "",
                ["2.5D"] = "",
            },
            ["TileMapComponent2D"] = new(StringComparer.Ordinal)
            {
                ["TileMapPath"] = "",
            },
            ["ButtonComponent2D"] = new(StringComparer.Ordinal)
            {
                ["IsActive"] = "",
                ["EffectiveArea"] = ",,,",
                ["Description"] = "",
            },
            ["RigidBodyComponent2D"] = new(StringComparer.Ordinal)
            {
                ["OffSetCollision"] = ",",
                ["Velocity"] = ",,",
                ["Collide"] = "",
                ["Mass"] = "",
            },
            ["AnimationComponent2D"] = new(StringComparer.Ordinal)
            {
                ["TextureAtlasPath"] = "",
                ["AnimationBindings"] = "",
                ["CurrentAnimationType"] = "",
            },
            ["FontComponent2D"] = new(StringComparer.Ordinal)
            {
                ["Texto"] = "",
                ["Font"] = "",
                ["IsVisible"] = "",
            },
        };

        /// <summary>
        /// Devuelve true si TODAS las propiedades de <paramref name="comp"/> coinciden con su valor inactivo
        /// declarado por <c>[UIComponentValue.inactiveValue]</c>. Usado por el loop de carga para saltarse
        /// componentes vacíos (reemplaza el viejo filtro contra EntityYTBXmlTemplate.GenerateNew()).
        /// </summary>
        internal static bool IsAllInactive(YTBComponents comp)
        {
            if (comp == null) return false;
            if (!_inactiveValuesByComponent.TryGetValue(comp.ComponentName, out var map)) return false;
            if (comp.Propiedades == null || comp.Propiedades.Count == 0) return true;
            foreach (var prop in comp.Propiedades)
            {
                if (!map.TryGetValue(prop.Item1, out var inactive)) return false;
                if (prop.Item2 != inactive) return false;
            }
            return true;
        }

        /// <summary>
        /// Mapa generado en build-time con los valores 'por defecto' por componente y propiedad.
        /// Usado por <c>EntityYTBXmlTemplate</c> como façade sobre el sistema de atributos.
        /// </summary>
        internal static readonly Dictionary<string, Dictionary<string, string>> _defaultValuesByComponent =
            new(StringComparer.Ordinal)
        {
            ["ModelComponent3D"] = new(StringComparer.Ordinal)
            {
                ["CollisionLayer"] = "",
                ["Velocity"] = "",
            },
            ["ModelComponent3D"] = new(StringComparer.Ordinal)
            {
                ["ModelPath"] = "",
                ["IsVisible"] = "true",
                ["SphereRadius"] = "0",
                ["OffsetSphere"] = "0,0,0",
            },
            ["InputComponent"] = new(StringComparer.Ordinal)
            {
                ["InputsInUse"] = "",
                ["KeyboardMappings"] = "MoveUp:W,\nMoveDown:S,\nMoveLeft:A,\nMoveRight:D,",
                ["GamePadIndex"] = "",
                ["MouseMappings"] = "",
            },
            ["ShaderComponent"] = new(StringComparer.Ordinal)
            {
                ["ShaderPath"] = "",
                ["IsActive"] = "true",
                ["params"] = "",
            },
            ["TransformComponent"] = new(StringComparer.Ordinal)
            {
                ["Size"] = "100,100,0",
                ["Scale"] = "1",
                ["Rotation"] = "0",
                ["Position"] = "0,0,1",
                ["SpriteEffects"] = "None",
                ["Color"] = "White",
            },
            ["ScriptComponent"] = new(StringComparer.Ordinal)
            {
                ["Scripts"] = "CSHARP&:&&;&",
            },
            ["SpriteComponent2D"] = new(StringComparer.Ordinal)
            {
                ["TextureAtlasPath"] = "",
                ["SpriteName"] = "",
                ["SourceRectangle"] = "0,0,0,0",
                ["IsVisible"] = "true",
                ["2.5D"] = "false",
            },
            ["TileMapComponent2D"] = new(StringComparer.Ordinal)
            {
                ["TileMapPath"] = "",
            },
            ["ButtonComponent2D"] = new(StringComparer.Ordinal)
            {
                ["IsActive"] = "true",
                ["EffectiveArea"] = "0,0,0,0",
                ["Description"] = "None",
            },
            ["RigidBodyComponent2D"] = new(StringComparer.Ordinal)
            {
                ["OffSetCollision"] = "0,0",
                ["Velocity"] = "0,0,0",
                ["Collide"] = "Solid",
                ["Mass"] = "0",
            },
            ["AnimationComponent2D"] = new(StringComparer.Ordinal)
            {
                ["TextureAtlasPath"] = "",
                ["AnimationBindings"] = "",
                ["CurrentAnimationType"] = "none",
            },
            ["FontComponent2D"] = new(StringComparer.Ordinal)
            {
                ["Texto"] = "Texto de ejemplo",
                ["Font"] = "Fonts/Hud",
                ["IsVisible"] = "true",
            },
        };

        internal static readonly Dictionary<string, Action<YotsubaEngine.Core.Entity.Yotsuba, YTBComponents, YotsubaEngine.Core.YotsubaGame.Scene, string, string>>?
            _autoGeneratedComponents = new(StringComparer.Ordinal)
        {
        };
    }
}
