<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
			<TargetFramework>net10.0</TargetFramework>
			<OutputType>Library</OutputType>
			<Configurations>Debug;Release;YTB</Configurations>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
	</PropertyGroup>
<PropertyGroup Condition="'$(Configuration)' == 'YTB'">
  <DefineConstants>$(DefineConstants);YTB;DEBUG;YOTSUBA</DefineConstants>
</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.5-preview.*">
			<PrivateAssets>All</PrivateAssets>
		</PackageReference>
		
	
		<PackageReference Include="Gum.MonoGame" Version="2026.2.23.1" />		
		<PackageReference Include="System.Drawing.Common" Version="10.0.3" />
</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Hexa.NET.ImGui-2.2.4\Hexa.NET.ImGui-2.2.4\Hexa.NET.ImGui\Hexa.NET.ImGui.csproj" />
		<ProjectReference Include="..\Hexa.NET.ImGui-2.2.4\Hexa.NET.ImGui-2.2.4\Hexa.NET.ImNodes\Hexa.NET.ImNodes.csproj" />
		<ProjectReference Include="..\Hexa.NET.ImGui-2.2.4\Hexa.NET.ImGui-2.2.4\Hexa.NET.ImPlot\Hexa.NET.ImPlot.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="ActionFiles\ImGuiEditor\" />
	  <Folder Include="Graphics\Multiplatform\UI\" />
	</ItemGroup>
	<ItemGroup Condition="'$(Configuration)' == 'YTB'">
		<None Update="imgui.ini">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
	  <!-- Ensure any font files placed under the engine's Fonts folder are copied to build output -->
	  <None Include="Fonts\**\*.*">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>


</Project>