using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace YotsubaEngine.YTBContentBuilder.Scripting
{
    public static class ScriptRegistryGenerator
    {
        public static void GenerateRegistry(string sourcePath, string outputPath)
        {
            //Console.WriteLine($"[ScriptRegistry] Buscando scripts en: {sourcePath}");
            var files = Directory.GetFiles(sourcePath, "*.cs", SearchOption.AllDirectories);
            var scriptsFound = new List<(string ClassName, string FullName)>();

            // Regex simple para detectar [Script] o [ScriptAttribute] y la definición de la clase
            // Nota: Para casos complejos, Roslyn es mejor, pero esto funciona para AOT simple.
            var attrRegex = new Regex(@"\[Script(Attribute)?\]");
            var classRegex = new Regex(@"public\s+(?:sealed\s+)?class\s+(\w+)\s*:\s*BaseScript");
            var namespaceRegex = new Regex(@"namespace\s+([\w\.]+)");

            foreach (var file in files)
            {
                //if (file.Contains("obj") || file.Contains("bin")) continue;

                string content = File.ReadAllText(file);

                if (attrRegex.IsMatch(content))
                {
                    var nsMatch = namespaceRegex.Match(content);
                    var classMatch = classRegex.Match(content);

                    if (classMatch.Success && nsMatch.Success)
                    {
                        string className = classMatch.Groups[1].Value;
                        string ns = nsMatch.Groups[1].Value;
                        string fullName = $"{ns}.{className}";

                        scriptsFound.Add((className, fullName));
                        //Console.WriteLine($"[ScriptRegistry] Script encontrado: {className}");
                    }
                }
            }

            WriteRegistryFile(scriptsFound, outputPath);
        }

        private static void WriteRegistryFile(List<(string ClassName, string FullName)> scripts, string outputPath)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Este archivo fue generado por CompiladorAssets.");
            sb.AppendLine("// No modifiques este archivo manualmente.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.IO;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using YotsubaEngine.Core.YotsubaGame.Scripting;");
            sb.AppendLine("");
            sb.AppendLine("namespace YotsubaEngine.Scripting");
            sb.AppendLine("{");
            sb.AppendLine("    public class ScriptRegistry : IScriptRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        public ScriptRegistry()");
            sb.AppendLine("        {");

            foreach (var script in scripts)
            {
                // Genera: { "NombreClase", () => new Namespace.NombreClase() },
                sb.AppendLine($"          Scripts.TryAdd(\"{script.ClassName}\", () => new {script.FullName}() );");
            }

            sb.AppendLine("        }");
            sb.AppendLine("");
            sb.AppendLine("        public override BaseScript Create(string scriptName)");
            sb.AppendLine("        {");
            sb.AppendLine("             scriptName = Path.GetFileNameWithoutExtension(scriptName);");
            sb.AppendLine("             ");
            sb.AppendLine("            if (Scripts.TryGetValue(scriptName, out var factory))");
            sb.AppendLine("            {");
            sb.AppendLine("                return factory();");
            sb.AppendLine("            }");
            sb.AppendLine("            return base.Create(scriptName);");
            sb.AppendLine("        }");
            sb.AppendLine("");

            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(outputPath + ".cs", sb.ToString());
            //Console.WriteLine($"[ScriptRegistry] Registro generado en: {outputPath}");
        }
    }
}
