using Microsoft.Xna.Framework.Audio;
using Microsoft.Xna.Framework.Media;

namespace YotsubaEngine.Audio
{
    /// <summary>
    /// Clase parcial para activos de audio; la otra parte es auto-generada por el content builder.
    /// <para>Partial class for audio assets; the other part is auto-generated by the content builder.</para>
    /// </summary>
    /// <remarks>
    /// This base partial exists to prevent compilation errors when no audio assets are present
    /// or when the generated file is accidentally deleted.
    /// Esta parte base existe para prevenir errores de compilación cuando no hay activos de audio
    /// o cuando el archivo generado se borra accidentalmente.
    /// </remarks>
    public static partial class AudioAssets
    {
        /// <summary>
        /// Indica si los activos de audio han sido inicializados.
        /// <para>Indicates whether audio assets have been initialized.</para>
        /// </summary>
        public static bool IsInitialized { get; private set; } = false;

        /// <summary>
        /// Inicializa el sistema de activos de audio.
        /// <para>Initializes the audio assets system.</para>
        /// </summary>
        /// <remarks>
        /// This method is called automatically by the generated partial class.
        /// Este método es llamado automáticamente por la clase parcial generada.
        /// </remarks>
        public static void Initialize()
        {
            if (!IsInitialized)
            {
                InitializeAudioAssets();
                IsInitialized = true;
            }
        }

        /// <summary>
        /// Hook method for the generated partial class to register audio assets.
        /// This method is automatically implemented by the AudioRegistryGenerator when
        /// audio files are found in the Assets folder during the content build process.
        /// If no audio files are present, this remains unimplemented and the call becomes a no-op.
        /// Método de enganche para que la clase parcial generada registre activos de audio.
        /// Este método es implementado automáticamente por el AudioRegistryGenerator cuando
        /// se encuentran archivos de audio en la carpeta Assets durante el proceso de construcción de contenido.
        /// Si no hay archivos de audio, permanece sin implementar y la llamada se convierte en no-op.
        /// </summary>
        static partial void InitializeAudioAssets();
    }
}
