<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Platforms>AnyCPU</Platforms>
    <Configurations>Debug;Release;YTB</Configurations>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'YTB'">
		<DefineConstants>DEBUG;YOTSUBA</DefineConstants>
	</PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.Native" Version="3.8.5-preview.*">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
	  <PackageReference Include="AvaloniaInside.MonoGame" Version="1.0.2" />

  </ItemGroup>

	<ItemGroup Condition="'$(Configuration)' != 'YTB'">
		<ProjectReference Include="..\..\Hexa.NET.ImGui-2.2.4\Hexa.NET.ImGui-2.2.4\Hexa.NET.ImGuizmo\Hexa.NET.ImGuizmo.csproj" />
		<ProjectReference Include="..\..\Hexa.NET.ImGui-2.2.4\Hexa.NET.ImGui-2.2.4\Hexa.NET.ImGui\Hexa.NET.ImGui.csproj" />
		<!--<PackageReference Include="Hexa.NET.ImGui" Version="2.2.4" />
		<PackageReference Include="Hexa.NET.ImGuizmo" Version="2.2.4" />
		<PackageReference Include="Hexa.NET.ImNodes" Version="2.2.4" />
		<PackageReference Include="Hexa.NET.ImPlot" Version="2.2.4" />-->
		<ProjectReference Include="..\..\Hexa.NET.ImGui-2.2.4\Hexa.NET.ImGui-2.2.4\Hexa.NET.ImNodes\Hexa.NET.ImNodes.csproj" />
		<ProjectReference Include="..\..\Hexa.NET.ImGui-2.2.4\Hexa.NET.ImGui-2.2.4\Hexa.NET.ImPlot\Hexa.NET.ImPlot.csproj" />
		<ProjectReference Include="..\..\Hexa.NET.ImGui-2.2.4\Hexa.NET.ImGui-2.2.4\Hexa.NET.ImGui.Backends\Hexa.NET.ImGui.Backends.csproj" />
	</ItemGroup>
  <ItemGroup>
	  <ProjectReference Include="..\..\Gum\GumCommon\GumCommon.csproj" />
	  <ProjectReference Include="..\..\Gum\MonoGameGum\MonoGameGum.csproj" />
	  <ProjectReference Include="..\..\YotsubaEngine\YotsubaEngine.csproj" />

  </ItemGroup>
	<ItemGroup>
		<None Update="Content\GumProject\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
  <!--<ItemGroup>
    <None Include="Assets\Gum\**\*">
      <Link>Content\Gum\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>-->
  <ItemGroup>
    <Folder Include="Assets\Effect\" />
    <Folder Include="Content\GumProject\" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Localization\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Localization\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>