// <auto-generated>
// Este archivo fue generado por CompiladorAssets.
// No modifiques este archivo manualmente.
// </auto-generated>
using System;
using System.IO;
using System.Collections.Generic;
using YotsubaEngine.Core.YotsubaGame.Scripting;

namespace YotsubaEngine.Scripting
{
    public class ScriptRegistry : IScriptRegistry
    {
        public ScriptRegistry()
        {
          Scripts.TryAdd("Bat", () => new SandBoxGame.Core.Scripts.Bat() );
          Scripts.TryAdd("Dimencion25", () => new SandBoxGame.Core.Scripts.Dimencion25() );
          Scripts.TryAdd("Slime", () => new SandBoxGame.Core.Scripts.Slime() );
          Scripts.TryAdd("Background", () => new SandBoxGame.Core.Scripts.HomeScreen.Background() );
          Scripts.TryAdd("GroundScript", () => new SandBoxGame.Core.Scripts.ModelScreen.GroundScript() );
          Scripts.TryAdd("HomeScreen", () => new SandBoxGame.Core.Scripts.Screens.HomeScreen() );
        }

        public override BaseScript Create(string scriptName)
        {
             scriptName = Path.GetFileNameWithoutExtension(scriptName);
             
            if (Scripts.TryGetValue(scriptName, out var factory))
            {
                return factory();
            }
            return base.Create(scriptName);
        }

    }
}
