// <auto-generated>
// Este archivo fue generado por CompiladorAssets.
// No modifiques este archivo manualmente.
// </auto-generated>
using System;
using System.IO;
using System.Collections.Generic;
using YotsubaEngine.Core.YotsubaGame.Scripting;

namespace YotsubaEngine.Scripting
{
    public class ScriptRegistry : IScriptRegistry
    {
        public ScriptRegistry()
        {
          Scripts.TryAdd("ModelExample", () => new SandBoxGame.Core.Scripts.ModelExample() );
        }

        public override BaseScript Create(string scriptName)
        {
             scriptName = Path.GetFileNameWithoutExtension(scriptName);
             
            if (Scripts.TryGetValue(scriptName, out var factory))
            {
                return factory();
            }
            return base.Create(scriptName);
        }

    }
}
