// <auto-generated>
// This file was generated by AudioRegistryGenerator.
// Do not modify this file manually.
// Este archivo fue generado por AudioRegistryGenerator.
// No modifiques este archivo manualmente.
// </auto-generated>

using Microsoft.Xna.Framework.Audio;
using Microsoft.Xna.Framework.Media;
using YotsubaEngine.Audio;
using YotsubaEngine.Core.System.YotsubaEngineCore;

namespace YotsubaEngine.Audio
{
    /// <summary>
    /// Auto-generated partial class containing all discovered audio assets.
    /// Clase parcial auto-generada que contiene todos los activos de audio descubiertos.
    /// </summary>
    public static partial class AudioAssets
    {
        public static partial void InitializeAudioAssets();
        public static partial void InitializeAudioAssets()
        {
            // Register sound effects / Registrar efectos de sonido

            // Register songs / Registrar canciones
        }

    }
}
