// <auto-generated>
// This file was generated by ModelRegistryGenerator.
// Do not modify this file manually.
// Este archivo fue generado por ModelRegistryGenerator.
// No modifiques este archivo manualmente.
// </auto-generated>

using Microsoft.Xna.Framework.Graphics;
using YotsubaEngine.Core.System.YotsubaEngineCore;
using YotsubaEngine.Graphics;
using YotsubaEngine.Core.YotsubaGame;

namespace YotsubaEngine.Graphics
{
    /// <summary>
    /// Auto-generated class containing all discovered 3D model assets.
    /// Clase auto-generada que contiene todos los modelos 3D descubiertos.
    /// </summary>
    public class ModelRegistry : IModelRegistry
    {
        /// <summary>
        /// Initializes the model registry and registers all discovered models.
        /// Inicializa el registro de modelos y registra todos los modelos descubiertos.
        /// </summary>
        public ModelRegistry()
        {
            // Register all discovered models / Registrar todos los modelos descubiertos
            RegisterModel("corona/crown");
            RegisterModel("FBX format/corridor-corner");
            RegisterModel("FBX format/corridor-end");
            RegisterModel("FBX format/corridor-intersection");
            RegisterModel("FBX format/corridor-junction");
            RegisterModel("FBX format/corridor-transition");
            RegisterModel("FBX format/corridor-wide-corner");
            RegisterModel("FBX format/corridor-wide-end");
            RegisterModel("FBX format/corridor-wide-intersection");
            RegisterModel("FBX format/corridor-wide-junction");
            RegisterModel("FBX format/corridor-wide");
            RegisterModel("FBX format/corridor");
            RegisterModel("FBX format/gate-door-window");
            RegisterModel("FBX format/gate-door");
            RegisterModel("FBX format/gate");
            RegisterModel("FBX format/room-corner");
            RegisterModel("FBX format/room-large-variation");
            RegisterModel("FBX format/room-large");
            RegisterModel("FBX format/room-small-variation");
            RegisterModel("FBX format/room-small");
            RegisterModel("FBX format/room-wide-variation");
            RegisterModel("FBX format/room-wide");
            RegisterModel("FBX format/stairs-wide");
            RegisterModel("FBX format/stairs");
            RegisterModel("FBX format/template-corner");
            RegisterModel("FBX format/template-detail");
            RegisterModel("FBX format/template-floor-big");
            RegisterModel("FBX format/template-floor-detail-a");
            RegisterModel("FBX format/template-floor-detail");
            RegisterModel("FBX format/template-floor-layer-raised");
            RegisterModel("FBX format/template-floor-layer");
            RegisterModel("FBX format/template-wall-corner");
            RegisterModel("FBX format/template-wall-detail-a");
            RegisterModel("FBX format/template-wall-half");
            RegisterModel("FBX format/template-wall-stairs");
            RegisterModel("FBX format/template-wall-top");
            RegisterModel("FBX format/template-wall");
            RegisterModel("Models/fbx/Dragon 2.5_fbx");
            RegisterModel("Models/FBX format/building-a");
            RegisterModel("Models/FBX format/building-b");
            RegisterModel("Models/FBX format/building-c");
            RegisterModel("Models/FBX format/building-d");
            RegisterModel("Models/FBX format/building-e");
            RegisterModel("Models/FBX format/building-f");
            RegisterModel("Models/FBX format/building-g");
            RegisterModel("Models/FBX format/building-h");
            RegisterModel("Models/FBX format/building-i");
            RegisterModel("Models/FBX format/building-j");
            RegisterModel("Models/FBX format/building-k");
            RegisterModel("Models/FBX format/building-l");
            RegisterModel("Models/FBX format/building-m");
            RegisterModel("Models/FBX format/building-n");
            RegisterModel("Models/FBX format/building-skyscraper-a");
            RegisterModel("Models/FBX format/building-skyscraper-b");
            RegisterModel("Models/FBX format/building-skyscraper-c");
            RegisterModel("Models/FBX format/building-skyscraper-d");
            RegisterModel("Models/FBX format/building-skyscraper-e");
            RegisterModel("Models/FBX format/detail-awning-wide");
            RegisterModel("Models/FBX format/detail-awning");
            RegisterModel("Models/FBX format/detail-overhang-wide");
            RegisterModel("Models/FBX format/detail-overhang");
            RegisterModel("Models/FBX format/detail-parasol-a");
            RegisterModel("Models/FBX format/detail-parasol-b");
            RegisterModel("Models/FBX format/low-detail-building-a");
            RegisterModel("Models/FBX format/low-detail-building-b");
            RegisterModel("Models/FBX format/low-detail-building-c");
            RegisterModel("Models/FBX format/low-detail-building-d");
            RegisterModel("Models/FBX format/low-detail-building-e");
            RegisterModel("Models/FBX format/low-detail-building-f");
            RegisterModel("Models/FBX format/low-detail-building-g");
            RegisterModel("Models/FBX format/low-detail-building-h");
            RegisterModel("Models/FBX format/low-detail-building-i");
            RegisterModel("Models/FBX format/low-detail-building-j");
            RegisterModel("Models/FBX format/low-detail-building-k");
            RegisterModel("Models/FBX format/low-detail-building-l");
            RegisterModel("Models/FBX format/low-detail-building-m");
            RegisterModel("Models/FBX format/low-detail-building-n");
            RegisterModel("Models/FBX format/low-detail-building-wide-a");
            RegisterModel("Models/FBX format/low-detail-building-wide-b");
            RegisterModel("Models/ground");
        }

        /// <summary>
        /// Static accessors for 3D models (cached on first access).
        /// Accesos estáticos para modelos 3D (cacheados en primer acceso).
        /// </summary>
        public static class Models
        {
            private static Model _crown;
            /// <summary>3D Model: crown (corona/crown)</summary>
            public static Model crown => _crown ??= YTBGlobalState.ContentManager.Load<Model>("corona/crown");

            private static Model _corridor_corner;
            /// <summary>3D Model: corridor-corner (FBX format/corridor-corner)</summary>
            public static Model corridor_corner => _corridor_corner ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/corridor-corner");

            private static Model _corridor_end;
            /// <summary>3D Model: corridor-end (FBX format/corridor-end)</summary>
            public static Model corridor_end => _corridor_end ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/corridor-end");

            private static Model _corridor_intersection;
            /// <summary>3D Model: corridor-intersection (FBX format/corridor-intersection)</summary>
            public static Model corridor_intersection => _corridor_intersection ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/corridor-intersection");

            private static Model _corridor_junction;
            /// <summary>3D Model: corridor-junction (FBX format/corridor-junction)</summary>
            public static Model corridor_junction => _corridor_junction ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/corridor-junction");

            private static Model _corridor_transition;
            /// <summary>3D Model: corridor-transition (FBX format/corridor-transition)</summary>
            public static Model corridor_transition => _corridor_transition ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/corridor-transition");

            private static Model _corridor_wide_corner;
            /// <summary>3D Model: corridor-wide-corner (FBX format/corridor-wide-corner)</summary>
            public static Model corridor_wide_corner => _corridor_wide_corner ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/corridor-wide-corner");

            private static Model _corridor_wide_end;
            /// <summary>3D Model: corridor-wide-end (FBX format/corridor-wide-end)</summary>
            public static Model corridor_wide_end => _corridor_wide_end ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/corridor-wide-end");

            private static Model _corridor_wide_intersection;
            /// <summary>3D Model: corridor-wide-intersection (FBX format/corridor-wide-intersection)</summary>
            public static Model corridor_wide_intersection => _corridor_wide_intersection ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/corridor-wide-intersection");

            private static Model _corridor_wide_junction;
            /// <summary>3D Model: corridor-wide-junction (FBX format/corridor-wide-junction)</summary>
            public static Model corridor_wide_junction => _corridor_wide_junction ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/corridor-wide-junction");

            private static Model _corridor_wide;
            /// <summary>3D Model: corridor-wide (FBX format/corridor-wide)</summary>
            public static Model corridor_wide => _corridor_wide ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/corridor-wide");

            private static Model _corridor;
            /// <summary>3D Model: corridor (FBX format/corridor)</summary>
            public static Model corridor => _corridor ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/corridor");

            private static Model _gate_door_window;
            /// <summary>3D Model: gate-door-window (FBX format/gate-door-window)</summary>
            public static Model gate_door_window => _gate_door_window ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/gate-door-window");

            private static Model _gate_door;
            /// <summary>3D Model: gate-door (FBX format/gate-door)</summary>
            public static Model gate_door => _gate_door ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/gate-door");

            private static Model _gate;
            /// <summary>3D Model: gate (FBX format/gate)</summary>
            public static Model gate => _gate ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/gate");

            private static Model _room_corner;
            /// <summary>3D Model: room-corner (FBX format/room-corner)</summary>
            public static Model room_corner => _room_corner ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/room-corner");

            private static Model _room_large_variation;
            /// <summary>3D Model: room-large-variation (FBX format/room-large-variation)</summary>
            public static Model room_large_variation => _room_large_variation ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/room-large-variation");

            private static Model _room_large;
            /// <summary>3D Model: room-large (FBX format/room-large)</summary>
            public static Model room_large => _room_large ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/room-large");

            private static Model _room_small_variation;
            /// <summary>3D Model: room-small-variation (FBX format/room-small-variation)</summary>
            public static Model room_small_variation => _room_small_variation ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/room-small-variation");

            private static Model _room_small;
            /// <summary>3D Model: room-small (FBX format/room-small)</summary>
            public static Model room_small => _room_small ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/room-small");

            private static Model _room_wide_variation;
            /// <summary>3D Model: room-wide-variation (FBX format/room-wide-variation)</summary>
            public static Model room_wide_variation => _room_wide_variation ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/room-wide-variation");

            private static Model _room_wide;
            /// <summary>3D Model: room-wide (FBX format/room-wide)</summary>
            public static Model room_wide => _room_wide ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/room-wide");

            private static Model _stairs_wide;
            /// <summary>3D Model: stairs-wide (FBX format/stairs-wide)</summary>
            public static Model stairs_wide => _stairs_wide ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/stairs-wide");

            private static Model _stairs;
            /// <summary>3D Model: stairs (FBX format/stairs)</summary>
            public static Model stairs => _stairs ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/stairs");

            private static Model _template_corner;
            /// <summary>3D Model: template-corner (FBX format/template-corner)</summary>
            public static Model template_corner => _template_corner ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/template-corner");

            private static Model _template_detail;
            /// <summary>3D Model: template-detail (FBX format/template-detail)</summary>
            public static Model template_detail => _template_detail ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/template-detail");

            private static Model _template_floor_big;
            /// <summary>3D Model: template-floor-big (FBX format/template-floor-big)</summary>
            public static Model template_floor_big => _template_floor_big ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/template-floor-big");

            private static Model _template_floor_detail_a;
            /// <summary>3D Model: template-floor-detail-a (FBX format/template-floor-detail-a)</summary>
            public static Model template_floor_detail_a => _template_floor_detail_a ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/template-floor-detail-a");

            private static Model _template_floor_detail;
            /// <summary>3D Model: template-floor-detail (FBX format/template-floor-detail)</summary>
            public static Model template_floor_detail => _template_floor_detail ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/template-floor-detail");

            private static Model _template_floor_layer_raised;
            /// <summary>3D Model: template-floor-layer-raised (FBX format/template-floor-layer-raised)</summary>
            public static Model template_floor_layer_raised => _template_floor_layer_raised ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/template-floor-layer-raised");

            private static Model _template_floor_layer;
            /// <summary>3D Model: template-floor-layer (FBX format/template-floor-layer)</summary>
            public static Model template_floor_layer => _template_floor_layer ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/template-floor-layer");

            private static Model _template_wall_corner;
            /// <summary>3D Model: template-wall-corner (FBX format/template-wall-corner)</summary>
            public static Model template_wall_corner => _template_wall_corner ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/template-wall-corner");

            private static Model _template_wall_detail_a;
            /// <summary>3D Model: template-wall-detail-a (FBX format/template-wall-detail-a)</summary>
            public static Model template_wall_detail_a => _template_wall_detail_a ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/template-wall-detail-a");

            private static Model _template_wall_half;
            /// <summary>3D Model: template-wall-half (FBX format/template-wall-half)</summary>
            public static Model template_wall_half => _template_wall_half ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/template-wall-half");

            private static Model _template_wall_stairs;
            /// <summary>3D Model: template-wall-stairs (FBX format/template-wall-stairs)</summary>
            public static Model template_wall_stairs => _template_wall_stairs ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/template-wall-stairs");

            private static Model _template_wall_top;
            /// <summary>3D Model: template-wall-top (FBX format/template-wall-top)</summary>
            public static Model template_wall_top => _template_wall_top ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/template-wall-top");

            private static Model _template_wall;
            /// <summary>3D Model: template-wall (FBX format/template-wall)</summary>
            public static Model template_wall => _template_wall ??= YTBGlobalState.ContentManager.Load<Model>("FBX format/template-wall");

            private static Model _Dragon_2_5_fbx;
            /// <summary>3D Model: Dragon 2.5_fbx (Models/fbx/Dragon 2.5_fbx)</summary>
            public static Model Dragon_2_5_fbx => _Dragon_2_5_fbx ??= YTBGlobalState.ContentManager.Load<Model>("Models/fbx/Dragon 2.5_fbx");

            private static Model _building_a;
            /// <summary>3D Model: building-a (Models/FBX format/building-a)</summary>
            public static Model building_a => _building_a ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/building-a");

            private static Model _building_b;
            /// <summary>3D Model: building-b (Models/FBX format/building-b)</summary>
            public static Model building_b => _building_b ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/building-b");

            private static Model _building_c;
            /// <summary>3D Model: building-c (Models/FBX format/building-c)</summary>
            public static Model building_c => _building_c ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/building-c");

            private static Model _building_d;
            /// <summary>3D Model: building-d (Models/FBX format/building-d)</summary>
            public static Model building_d => _building_d ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/building-d");

            private static Model _building_e;
            /// <summary>3D Model: building-e (Models/FBX format/building-e)</summary>
            public static Model building_e => _building_e ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/building-e");

            private static Model _building_f;
            /// <summary>3D Model: building-f (Models/FBX format/building-f)</summary>
            public static Model building_f => _building_f ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/building-f");

            private static Model _building_g;
            /// <summary>3D Model: building-g (Models/FBX format/building-g)</summary>
            public static Model building_g => _building_g ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/building-g");

            private static Model _building_h;
            /// <summary>3D Model: building-h (Models/FBX format/building-h)</summary>
            public static Model building_h => _building_h ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/building-h");

            private static Model _building_i;
            /// <summary>3D Model: building-i (Models/FBX format/building-i)</summary>
            public static Model building_i => _building_i ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/building-i");

            private static Model _building_j;
            /// <summary>3D Model: building-j (Models/FBX format/building-j)</summary>
            public static Model building_j => _building_j ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/building-j");

            private static Model _building_k;
            /// <summary>3D Model: building-k (Models/FBX format/building-k)</summary>
            public static Model building_k => _building_k ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/building-k");

            private static Model _building_l;
            /// <summary>3D Model: building-l (Models/FBX format/building-l)</summary>
            public static Model building_l => _building_l ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/building-l");

            private static Model _building_m;
            /// <summary>3D Model: building-m (Models/FBX format/building-m)</summary>
            public static Model building_m => _building_m ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/building-m");

            private static Model _building_n;
            /// <summary>3D Model: building-n (Models/FBX format/building-n)</summary>
            public static Model building_n => _building_n ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/building-n");

            private static Model _building_skyscraper_a;
            /// <summary>3D Model: building-skyscraper-a (Models/FBX format/building-skyscraper-a)</summary>
            public static Model building_skyscraper_a => _building_skyscraper_a ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/building-skyscraper-a");

            private static Model _building_skyscraper_b;
            /// <summary>3D Model: building-skyscraper-b (Models/FBX format/building-skyscraper-b)</summary>
            public static Model building_skyscraper_b => _building_skyscraper_b ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/building-skyscraper-b");

            private static Model _building_skyscraper_c;
            /// <summary>3D Model: building-skyscraper-c (Models/FBX format/building-skyscraper-c)</summary>
            public static Model building_skyscraper_c => _building_skyscraper_c ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/building-skyscraper-c");

            private static Model _building_skyscraper_d;
            /// <summary>3D Model: building-skyscraper-d (Models/FBX format/building-skyscraper-d)</summary>
            public static Model building_skyscraper_d => _building_skyscraper_d ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/building-skyscraper-d");

            private static Model _building_skyscraper_e;
            /// <summary>3D Model: building-skyscraper-e (Models/FBX format/building-skyscraper-e)</summary>
            public static Model building_skyscraper_e => _building_skyscraper_e ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/building-skyscraper-e");

            private static Model _detail_awning_wide;
            /// <summary>3D Model: detail-awning-wide (Models/FBX format/detail-awning-wide)</summary>
            public static Model detail_awning_wide => _detail_awning_wide ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/detail-awning-wide");

            private static Model _detail_awning;
            /// <summary>3D Model: detail-awning (Models/FBX format/detail-awning)</summary>
            public static Model detail_awning => _detail_awning ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/detail-awning");

            private static Model _detail_overhang_wide;
            /// <summary>3D Model: detail-overhang-wide (Models/FBX format/detail-overhang-wide)</summary>
            public static Model detail_overhang_wide => _detail_overhang_wide ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/detail-overhang-wide");

            private static Model _detail_overhang;
            /// <summary>3D Model: detail-overhang (Models/FBX format/detail-overhang)</summary>
            public static Model detail_overhang => _detail_overhang ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/detail-overhang");

            private static Model _detail_parasol_a;
            /// <summary>3D Model: detail-parasol-a (Models/FBX format/detail-parasol-a)</summary>
            public static Model detail_parasol_a => _detail_parasol_a ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/detail-parasol-a");

            private static Model _detail_parasol_b;
            /// <summary>3D Model: detail-parasol-b (Models/FBX format/detail-parasol-b)</summary>
            public static Model detail_parasol_b => _detail_parasol_b ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/detail-parasol-b");

            private static Model _low_detail_building_a;
            /// <summary>3D Model: low-detail-building-a (Models/FBX format/low-detail-building-a)</summary>
            public static Model low_detail_building_a => _low_detail_building_a ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/low-detail-building-a");

            private static Model _low_detail_building_b;
            /// <summary>3D Model: low-detail-building-b (Models/FBX format/low-detail-building-b)</summary>
            public static Model low_detail_building_b => _low_detail_building_b ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/low-detail-building-b");

            private static Model _low_detail_building_c;
            /// <summary>3D Model: low-detail-building-c (Models/FBX format/low-detail-building-c)</summary>
            public static Model low_detail_building_c => _low_detail_building_c ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/low-detail-building-c");

            private static Model _low_detail_building_d;
            /// <summary>3D Model: low-detail-building-d (Models/FBX format/low-detail-building-d)</summary>
            public static Model low_detail_building_d => _low_detail_building_d ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/low-detail-building-d");

            private static Model _low_detail_building_e;
            /// <summary>3D Model: low-detail-building-e (Models/FBX format/low-detail-building-e)</summary>
            public static Model low_detail_building_e => _low_detail_building_e ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/low-detail-building-e");

            private static Model _low_detail_building_f;
            /// <summary>3D Model: low-detail-building-f (Models/FBX format/low-detail-building-f)</summary>
            public static Model low_detail_building_f => _low_detail_building_f ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/low-detail-building-f");

            private static Model _low_detail_building_g;
            /// <summary>3D Model: low-detail-building-g (Models/FBX format/low-detail-building-g)</summary>
            public static Model low_detail_building_g => _low_detail_building_g ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/low-detail-building-g");

            private static Model _low_detail_building_h;
            /// <summary>3D Model: low-detail-building-h (Models/FBX format/low-detail-building-h)</summary>
            public static Model low_detail_building_h => _low_detail_building_h ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/low-detail-building-h");

            private static Model _low_detail_building_i;
            /// <summary>3D Model: low-detail-building-i (Models/FBX format/low-detail-building-i)</summary>
            public static Model low_detail_building_i => _low_detail_building_i ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/low-detail-building-i");

            private static Model _low_detail_building_j;
            /// <summary>3D Model: low-detail-building-j (Models/FBX format/low-detail-building-j)</summary>
            public static Model low_detail_building_j => _low_detail_building_j ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/low-detail-building-j");

            private static Model _low_detail_building_k;
            /// <summary>3D Model: low-detail-building-k (Models/FBX format/low-detail-building-k)</summary>
            public static Model low_detail_building_k => _low_detail_building_k ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/low-detail-building-k");

            private static Model _low_detail_building_l;
            /// <summary>3D Model: low-detail-building-l (Models/FBX format/low-detail-building-l)</summary>
            public static Model low_detail_building_l => _low_detail_building_l ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/low-detail-building-l");

            private static Model _low_detail_building_m;
            /// <summary>3D Model: low-detail-building-m (Models/FBX format/low-detail-building-m)</summary>
            public static Model low_detail_building_m => _low_detail_building_m ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/low-detail-building-m");

            private static Model _low_detail_building_n;
            /// <summary>3D Model: low-detail-building-n (Models/FBX format/low-detail-building-n)</summary>
            public static Model low_detail_building_n => _low_detail_building_n ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/low-detail-building-n");

            private static Model _low_detail_building_wide_a;
            /// <summary>3D Model: low-detail-building-wide-a (Models/FBX format/low-detail-building-wide-a)</summary>
            public static Model low_detail_building_wide_a => _low_detail_building_wide_a ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/low-detail-building-wide-a");

            private static Model _low_detail_building_wide_b;
            /// <summary>3D Model: low-detail-building-wide-b (Models/FBX format/low-detail-building-wide-b)</summary>
            public static Model low_detail_building_wide_b => _low_detail_building_wide_b ??= YTBGlobalState.ContentManager.Load<Model>("Models/FBX format/low-detail-building-wide-b");

            private static Model _ground;
            /// <summary>3D Model: ground (Models/ground)</summary>
            public static Model ground => _ground ??= YTBGlobalState.ContentManager.Load<Model>("Models/ground");

        }
    }
}
