// <auto-generated>
// This file was generated by ModelRegistryGenerator.
// Do not modify this file manually.
// Este archivo fue generado por ModelRegistryGenerator.
// No modifiques este archivo manualmente.
// </auto-generated>

using Microsoft.Xna.Framework.Graphics;
using YotsubaEngine.Core.System.YotsubaEngineCore;
using YotsubaEngine.Graphics;
using YotsubaEngine.Core.YotsubaGame;

namespace YotsubaEngine.Graphics
{
    /// <summary>
    /// Auto-generated class containing all discovered 3D model assets.
    /// Clase auto-generada que contiene todos los modelos 3D descubiertos.
    /// </summary>
    public class ModelRegistry : IModelRegistry
    {
        /// <summary>
        /// Initializes the model registry and registers all discovered models.
        /// Inicializa el registro de modelos y registra todos los modelos descubiertos.
        /// </summary>
        public ModelRegistry()
        {
            // Register all discovered models / Registrar todos los modelos descubiertos
            RegisterModel("Castle/Castle");
        }

        /// <summary>
        /// Static accessors for 3D models (cached on first access).
        /// Accesos estáticos para modelos 3D (cacheados en primer acceso).
        /// </summary>
        public static class Models
        {
            private static Model _Castle;
            /// <summary>3D Model: Castle (Castle/Castle)</summary>
            public static Model Castle => _Castle ??= YTBGlobalState.ContentManager.Load<Model>("Castle/Castle");

        }
    }
}
